# Generated by Django 3.2.8 on 2021-11-26 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(default=-1.0, max_length=20),
            preserve_default=False,
        ),
    ]
