# Generated by Django 3.2.8 on 2021-11-29 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0007_alter_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='post',
            name='usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='comentarios',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='feed.comentario'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='posts',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='feed.post'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario_fk',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
