# Generated by Django 3.2.8 on 2021-11-29 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0008_auto_20211129_0147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='actualizado_en',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='comentarios',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='posts',
        ),
        migrations.AddField(
            model_name='comentario',
            name='comentador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feed.usuario'),
        ),
        migrations.AddField(
            model_name='post',
            name='posteador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feed.usuario'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='feed.post'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
