# Generated by Django 3.2.8 on 2021-11-29 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0014_alter_comentario_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pre_contendio',
            field=models.TextField(default=-1.0),
            preserve_default=False,
        ),
    ]
