# Generated by Django 3.2.8 on 2021-11-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0016_rename_pre_contendio_post_pre_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tipo_17_ODS',
            field=models.CharField(choices=[(1, 'Fin de la pobreza'), (2, 'Hambre cero'), (3, 'Salud y bienestar'), (4, 'Educación de calidad'), (5, 'Igualdad de género'), (6, 'Agua limpia y saneamiento'), (7, 'Energía asequible y no contaminante'), (8, 'Trabajo y crecimiento económico'), (9, 'Industria, innovación e infraestructura'), (10, 'Reducción de las desigualdades'), (11, 'Ciudades y comunidades sostenibles'), (12, 'Producción y consumo responsables'), (13, 'Acción por el clima'), (14, 'Vida submarina'), (15, 'Vida de ecosistemas terrestres'), (16, 'Paz y justicia para todos'), (17, 'Alianzas para lograr los objetivos')], default=1, max_length=50),
        ),
    ]
