# Generated by Django 3.2.8 on 2021-11-30 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0017_post_tipo_17_ods'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagen',
            field=models.ImageField(default='feed/static/imagen_post/default.jpg', upload_to='feed'),
        ),
    ]
