# Generated by Django 3.2.8 on 2021-11-30 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0018_post_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(default='feed/static/imagenes_post/default.jpg', upload_to='feed'),
        ),
    ]
