# Generated by Django 3.2.8 on 2021-11-30 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0021_auto_20211130_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(default='feed/static/images/default.jpg', upload_to='feed'),
        ),
    ]
