# Generated by Django 3.2.8 on 2021-12-01 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0023_alter_post_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.FileField(default='feed/static/images/default.jpg', upload_to='imagenes_posts'),
        ),
    ]
