# Generated by Django 3.2.8 on 2021-12-01 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0024_alter_post_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.FileField(default='fotos_perfil/default.png', upload_to='fotos_perfil'),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.FileField(default='feed/static/images/post_default.jpg', upload_to='imagenes_posts'),
        ),
    ]
