# Generated by Django 3.2.8 on 2021-12-01 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0025_auto_20211201_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.FileField(default='fotos_perfil/foto_default.png', upload_to='fotos_perfil'),
        ),
    ]
