# Generated by Django 3.2.8 on 2021-12-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0027_auto_20211201_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categoria',
            field=models.ManyToManyField(default=None, to='feed.categoria'),
        ),
    ]
