# Generated by Django 3.2.8 on 2021-12-02 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0038_remove_tipo_usuario_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.FileField(default='foto_default.jpg', upload_to='fotos_perfil'),
        ),
    ]
