# Generated by Django 3.2.8 on 2021-12-03 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0041_alter_post_posteador'),
    ]

    operations = [
        migrations.CreateModel(
            name='reaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('me_gusta', models.BooleanField(default=False)),
                ('no_megusta', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.post')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.usuario')),
            ],
        ),
        migrations.RemoveField(
            model_name='nomegusta',
            name='post',
        ),
        migrations.RemoveField(
            model_name='nomegusta',
            name='usuario',
        ),
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(default='categoria_default.png', upload_to='categoria'),
        ),
        migrations.DeleteModel(
            name='megusta',
        ),
        migrations.DeleteModel(
            name='nomegusta',
        ),
    ]
