# Generated by Django 3.2.8 on 2021-12-05 06:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0044_notificaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificaciones',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
